### PR TITLE
Issue 1001 - statistics/graph sorting

### PR DESCRIPTION
**Pull request by michaeljon**
Moving fix to post release branch per PR request. Addresses issue with graph x-axis sorting and sorting of charts on page.

Issue (https://github.com/Ensembl/ensembl-vep/issues/1001).
Link: [JIRA](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4244)

### CODE REVIEW

**Comment by michaeljon** [comment]
Working on getting a VM with perl 5.10 to chase this down.

**Comment by diegomscoelho** [comment]
Hi @michaeljon, I've refactored a bit your solution. It has worked but I think we can concentrate everything simply on `sort_keys` function.

Feel free to test it again. If you find it OK, I can approve and merge your PR.

**Review by diegomscoelho — COMMENTED** [review]
Hi @michaeljon, I've refactored a bit your solution. It has worked but I think we can concentrate everything simply on sort_keys function.

Feel free to test it again. If you find it OK, I can approve and merge your PR.

**Review by olaaustine — APPROVED** [review]
All good!

**Pull request merged**
