### PR TITLE
Fixed Original allele where allele string not defined

### PR DESCRIPTION
**Pull request by likhitha-surapaneni**
Bugfix for [ensembl-vep#1313](https://github.com/Ensembl/ensembl-vep/pull/1313)

For SVs, allele_string is not defined. In such a case Original allele points to SO term

### CODE REVIEW

**Review by nuno-agostinho — APPROVED** [review]
Tested and working with:

`1      713044  CNV_gs_CNV_1_713044_755966 C <CN=0> . PASS END=755966;SVTYPE=DEL`

Thanks @likhitha-surapaneni!

**Comment by nuno-agostinho** [comment]
This will be backported to `release/110`.

**Comment by nuno-agostinho** [comment]
Is this PR replaced with #1444? Can we close this PR?

**Comment by likhitha-surapaneni** [comment]
Yes, that's right @nuno-agostinho. https://github.com/Ensembl/ensembl-vep/pull/1444 replaces this

**Pull request closed without merging**
