### PR TITLE
Fix interpretation issue when following entries have similar coordina…

### PR DESCRIPTION
**Pull request by ens-lgil**
…tes but on different chromosomes in the input file

### CODE REVIEW

**Comment by dglemos** [comment]
Are you going to add tests for e97?

**Comment by ens-lgil** [comment]
Yes, I am planning to add them today.
I wanted to see if the tests on the similar PR on `release/96` would pass.

**Comment by ens-lgil** [comment]
Tests added

**Comment by ens-lgil** [comment]
Will have to do a `Squash and merge` for this PR

**Pull request merged**
