### PR TITLE
Changes to the check ref

### PR DESCRIPTION
**Pull request by olaaustine**
[ENSVAR-4844](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4844)
#1243

### CODE REVIEW

**Comment by likhitha-surapaneni** [comment]
Hi @olaaustine ,

Thank you for the PR.

It seems to fail for the cases similar to the original issue. For example, `chr13   32900399        .       AGT     A       .` is not marked as failed but `chr13   32900399        .       AGT     G       .` is marked as failed.

**Comment by olaaustine** [comment]
> Hi @likhitha-surapaneni,
In VEP non vcf output, it reports the first variant and second variant as 
```
91860879	13:32900400-32900401	-	ENSG00000226968	ENST00000421002Transcript	intron_variant,non_coding_transcript_variant	-	-	IMPACT=MODIFIER;STRAND=-1
91860879	13:32900399-32900401	G	ENSG00000226968	ENST00000421002Transcript	intron_variant,non_coding_transcript_variant	-	-	IMPACT=MODIFIER;STRAND=-1;CHECK_REF=failed
```

In VEP vcf output, 
```
13	32900399	91860879	AGT	A	.	PASS	CSQ=-|intron_variant&non_coding_transcript_variant|MODIFIER|LINC00423|ENSG00000226968|Transcript|ENST00000421002|lncRNA||3/3||||||||||-1||HGNC|HGNC:42758|
13	32900399	91860879	AGT	G	.	PASS	CSQ=G|intron_variant&non_coding_transcript_variant|MODIFIER|LINC00423|ENSG00000226968|Transcript|ENST00000421002|lncRNA||3/3||||||||||-1||HGNC|HGNC:42758|failed
```
Even though the same result as above, the way the output is presented is different as it shows from position 32900399. I agree that this something we need to bring up with the team.

**Comment by likhitha-surapaneni** [comment]
This is a result of `check_ref` flag checking the stripped reference allele string. Taking processing time into account, it has been decided to update the documentation related to `check_ref` to make it clear.

**Comment by likhitha-surapaneni** [comment]
Looks good to me.

**Review by likhitha-surapaneni — APPROVED** [review]

**Pull request merged**
