### PR TITLE
Update slurm profile and resource limits

### PR DESCRIPTION
**Pull request by veidenberg**
This PR updates the slurm profile based on testing on our slurm cluster:
* Enable singularity on slurm
* Increase memory limit for VEP (for running without caches)

### CODE REVIEW

**Comment by veidenberg** [comment]
@nuno-agostinho @nakib103 these updates enabled us to run the pipeline on our cluster. Please take a look whether it's worth merging (for some reason I couldn't add reviewers).

**Comment by nuno-agostinho** [comment]
Hi @veidenberg!

@nakib103 and I think that the `slurm` profile should not include the Singularity configuration, as a user may want to use Docker instead when using that profile.

Instead, we propose to create a new profile with the website-specific configuration, like so:

```
ensembl {
  process.executor = 'slurm'
  singularity.enabled    = true
  singularity.autoMounts = true

  withName: runVEP {
    memory = 32.GB
  }
}
```

What do you think?

**Comment by veidenberg** [comment]
Makes sense. Config updated and tested.

**Review by nuno-agostinho — APPROVED** [review]
Thanks for the changes, @veidenberg. Looks good to me!

**Pull request merged**
