### PR TITLE
Fix missing population frequency when the flag '--filter_common' is used

### PR DESCRIPTION
**Pull request by ens-lgil**

### CODE REVIEW

**Comment by at7** [comment]
Can you please remind me why you are deleting the option?

**Comment by ens-lgil** [comment]
This option removed the population frequency (1KG, gnomAD,...) when we used the `--filter_common` flag.
This might be due to an older setting in the former VEP code

**Comment by ens-lgil** [comment]
@ima23 did you merged it to `release/94` as well ?

**Comment by ima23** [comment]
I've merged it on release/94 too. Thanks for checking!

**Pull request merged**
