### PR TITLE
Update Stats.pm

### PR DESCRIPTION
**Pull request by epaule**
breaks on $b for names like chromosome "3R"

### CODE REVIEW

**Comment by at7** [comment]
We recently fixed this for 98 https://github.com/Ensembl/ensembl-vep/pull/562/files I will close your PR and submit the same we also use for 98. I will also need to update the sub version. I let you know when the fix is in.

**Comment by epaule** [comment]
thanks, my VEP checkout was from 7 days ago, so it didn't include https://github.com/Ensembl/ensembl-vep/pull/562/commits/f29209def4f1c7f4463ea4709abb31d8793c49a7

**Comment by at7** [comment]
No problem. Are you working with release/97 or 98? Do you need the fix on release/97

**Comment by epaule** [comment]
I used master of 7 days ago, but github defaulted to 97 when I did the pull request. I guess that is the default branch at the moment. So all good.

**Pull request closed without merging**
