### PR TITLE
Bugfix/validate vf by allele length

### PR DESCRIPTION
**Pull request by at7**
Web team reported a VEP issue caused by variants whose reference allele were thousands of bp long. I set a threshold of 50 bp for input allele length before the variant is failing the validation step.

### CODE REVIEW

**Comment by at7** [comment]
@ens-lgil Do we need to increment VEP_SUB_VERSION?

**Comment by ens-lgil** [comment]
Yes we will need to update the subversion.
However there is an other PR pending at the moment with the subversion `2`

**Comment by at7** [comment]
I will do more tests to determine the right allele length for setting the threshold.

**Comment by at7** [comment]
Some  more [investigation](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-1642) required to define the right threshold

**Pull request closed without merging**
