### PR TITLE
Stanardising command line arguments to match variables in the script

### PR DESCRIPTION
**Pull request by dbolser**
Minor, but reduces confusion. Tested and works fine.

### CODE REVIEW

**Review by likhitha-surapaneni — APPROVED** [review]
Thank you @dbolser. Tested and looks good to me.

**Comment by likhitha-surapaneni** [comment]
Hi @dbolser, thank you. Can you please make the PR with `postreleasefix/111` as the base branch?

**Comment by dbolser** [comment]
I tried to change the PR branches but failed...

**Comment by dbolser** [comment]
I really messed up this PR! Good that it's closed... I'll delete the mangled fork that I created.

See: https://github.com/Ensembl/ensembl-vep/pull/1523

**Pull request closed without merging**
